#!/bin/bash
codes="$(lsusb | grep Pixel | cut -d' ' -f6)"
if test $codes
then
true
else
echo "no device"
exit
fi
vid=$(echo "$codes" | cut -d':' -f1)
pid=$(echo "$codes" | cut -d':' -f2)
sudo gio trash /etc/udev/rules.d/51-android.rules
sudo touch /etc/udev/rules.d/51-android.rules
echo "SUBSYSTEM==\"usb\", ATTR{idVendor}==\""$vid"\", ATTR{idProduct}==\""$pid"\", MODE=\"0666\", GROUP=\"plugdev\"" | sudo tee -a /etc/udev/rules.d/51-android.rules
sudo udevadm control --reload-rules
echo "re-plug your device"
